@token = eyJhbGciOiJSUzI1NiIsImtpZCI6IkRldmVsb3BtZW50IiwidHlwIjoiYXQrand0In0.eyJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo1MDAxIiwibmJmIjoxNjY2NjEwNTU2LCJpYXQiOjE2NjY2MTA1NTYsImV4cCI6MTY2NjYxNDE1NiwiYXVkIjoiQ1JNLkFwaUFQSSIsInNjb3BlIjpbIm9wZW5pZCIsInByb2ZpbGUiLCJDUk0uQXBpQVBJIl0sImFtciI6WyJwd2QiXSwiY2xpZW50X2lkIjoicmVtaXgiLCJzdWIiOiJmYjZlMGVlMi00MTg0LTRhNmUtYjY0ZS02OTM0ZTYxMmViYTkiLCJhdXRoX3RpbWUiOjE2NjY2MTA1NTYsImlkcCI6ImxvY2FsIiwic2lkIjoiMzlEQUJFRDlEMzExODU3REFGRUJCRDI0QzYxOUJBMjYiLCJqdGkiOiIyNTQxMTM5NzEzNjE1QTc2NTZDQTI5NDY3MjFCRDBBNiJ9.nWwgrA0mgcZfJs1YrTb9JApGyt2WxPRW6ydUekoQrgc5FK6vQYW9l1nk6mUfeNz4x7dAzKDSlpSc3n58xuxs4XqB3dTtOEfKUoJaTjBIms55mTytqDEFWCv_PSQnTNVKkS7OpzX2fz4JyFAhwKotVSFLPVfih53EKkNacvKXWTOmlcZ3s1zQI6Iz4QwC7zgJB2A7C8rFOstGJOVOHhBGceU8w7cmSs_26a-Od2Hk1A1JChPtSae6uww56-WFW63mNQFvZMEhK8YMjYM6_jq6U2CrN1_hGU3zKGi466Ry0BSJVCo5XfsazGCeKpCG312sPUZjvSsgM7VUTNgA5t30qg

### /token (client_credentials)
POST https://localhost:5001/connect/token
Content-Type: application/x-www-form-urlencoded
Authorization: Basic cmVtaXg6c2VjcmV0

grant_type=client_credentials&scope=company.read

### /authorize

GET https://localhost:5001/connect/authorize
  ?client_id=remix
  &redirect_uri=http://localhost:3000/authentication/login-callback
  &response_type=code
  &scope=openid%20profile%20CRM.ApiAPI

### /token (authorization_code)
POST https://localhost:5001/connect/token
Content-Type: application/x-www-form-urlencoded
Authorization: Basic cmVtaXg6c2VjcmV0

code=3C82BDBE327AC1165DD97E261CE30A2ABB9B314001122C15F126CB6F9528712D&client_id=remix&grant_type=authorization_code&redirect_uri=http://localhost:3000/authentication/login-callback

### /endsession

GET https://localhost:5001/connect/endsession
  ?post_logout_redirect_uri=http://localhost:3000/login
  &id_token_hint=eyJhbGciOiJSUzI1NiIsImtpZCI6IkRldmVsb3BtZW50IiwidHlwIjoiSldUIn0.eyJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo1MDAxIiwibmJmIjoxNjY2MjcyNzk0LCJpYXQiOjE2NjYyNzI3OTQsImV4cCI6MTY2NjI3MzA5NCwiYXVkIjoicmVtaXgiLCJhbXIiOlsicHdkIl0sIm5vbmNlIjoibm9uY2UiLCJhdF9oYXNoIjoiVk12YjZGVmhtZnZLN3B4dnRFcGs5dyIsInNpZCI6IkE4RDdDOERGRDRCMzdCRTc1MkYyQzREMjc3OUIzNEE0Iiwic3ViIjoiZmI2ZTBlZTItNDE4NC00YTZlLWI2NGUtNjkzNGU2MTJlYmE5IiwiYXV0aF90aW1lIjoxNjY2MjcyMzY1LCJpZHAiOiJsb2NhbCIsInByZWZlcnJlZF91c2VybmFtZSI6ImFkbWluaXN0cmF0b3JAbG9jYWxob3N0IiwibmFtZSI6ImFkbWluaXN0cmF0b3JAbG9jYWxob3N0In0.e3rSBqpuM5GXJWxeVRXPgE95iWTRsq8F7I9lpBjXHJikpeVS2n1li77spabT3rNmsdeKKhfJvo89HHecZAyljioPOfUFFAAcz5BC4EuQlJbOMa4YThEyoKsSedbhi7KyaIkQZWhIg8MtwOvkAbZZuG4Dz-biOS_qh2UziwIFW1zNCYkZtTNaJmvZXgDT4qxtUS5pelPkwf_mwpKF-EJ8KtZnNxMBlp6seyW0q6iOydiaD15T9n1Gu-vh7PkX_Xe576EfCTN-OLznnwdLo33hK6E56LMf6hVFeGdYWrUQqbQ-wNvOLPbcFm3P64ZbV9RgiCkerfqtZeEonnNf3ecttw

###

GET https://localhost:5001/Companies
Authorization: Bearer {{token}}

###

POST https://localhost:5001/Companies
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "foo"
}
